#!/usr/bin/env bash
# Builds the Rust FFI crate for every platform the workspace consumes:
#
#   RustFFI.xcframework                        (SwiftPM binaryTarget path)
#   Kmp/api/src/androidMain/jniLibs/*          (System.loadLibrary("rust_ffi"))
#   Rust/pkg/                                  (npm("rust_ffi", ...) in build.gradle.kts)
#
# NDK linker/env vars for the android targets come from Rust/.cargo/config.toml.
# Requires `wasm-bindgen` CLI; installed on demand if missing.
set -euo pipefail

export PATH="$HOME/.cargo/bin:$PATH"

# xmp_toolkit's C++ code emits `__chkstk_darwin`, only present on iOS 12+ /
# macOS 10.14+. Match Swift Package's Package.swift platform floors here.
export IPHONEOS_DEPLOYMENT_TARGET=14.0
export MACOSX_DEPLOYMENT_TARGET=11.0

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT/Rust"

APPLE_TARGETS=(
  aarch64-apple-ios
  aarch64-apple-ios-sim
  x86_64-apple-ios
  aarch64-apple-darwin
  x86_64-apple-darwin
)

ANDROID_PAIRS=(
  aarch64-linux-android:arm64-v8a
  armv7-linux-androideabi:armeabi-v7a
  x86_64-linux-android:x86_64
  i686-linux-android:x86
)

rustup target add "${APPLE_TARGETS[@]}"
rustup target add wasm32-unknown-unknown
for pair in "${ANDROID_PAIRS[@]}"; do
  rustup target add "${pair%%:*}"
done

command -v wasm-bindgen >/dev/null || cargo install wasm-bindgen-cli

########################################
# Apple
########################################
echo ">> apple targets"
for t in "${APPLE_TARGETS[@]}"; do
  cargo build --release --target "$t"
done

mkdir -p target/ios-sim-universal/release
lipo -create \
  target/aarch64-apple-ios-sim/release/librust_ffi.a \
  target/x86_64-apple-ios/release/librust_ffi.a \
  -output target/ios-sim-universal/release/librust_ffi.a

mkdir -p target/macos-universal/release
lipo -create \
  target/aarch64-apple-darwin/release/librust_ffi.a \
  target/x86_64-apple-darwin/release/librust_ffi.a \
  -output target/macos-universal/release/librust_ffi.a

rm -rf "$ROOT/RustFFI.xcframework"
xcodebuild -create-xcframework \
  -library target/aarch64-apple-ios/release/librust_ffi.a       -headers include \
  -library target/ios-sim-universal/release/librust_ffi.a       -headers include \
  -library target/macos-universal/release/librust_ffi.a         -headers include \
  -output "$ROOT/RustFFI.xcframework"

########################################
# Android
########################################
echo ">> android targets"
JNI_LIBS="$ROOT/Kmp/api/src/androidMain/jniLibs"
rm -rf "$JNI_LIBS"
for pair in "${ANDROID_PAIRS[@]}"; do
  triple="${pair%%:*}"
  abi="${pair##*:}"
  cargo build --release --target "$triple"
  mkdir -p "$JNI_LIBS/$abi"
  cp "target/$triple/release/librust_ffi.so" "$JNI_LIBS/$abi/librust_ffi.so"
done

########################################
# WebAssembly
########################################
echo ">> wasm target"
cargo build --release --target wasm32-unknown-unknown
rm -rf pkg
wasm-bindgen "target/wasm32-unknown-unknown/release/rust_ffi.wasm" \
  --out-dir pkg \
  --target web

# Inline the .wasm INTO the glue JS as base64, then delete the .wasm. This makes
# pkg/rust_ffi.js a single self-contained ES module: init() decodes the embedded
# bytes and does WebAssembly.instantiate(bytes) — no runtime fetch, no separate
# .wasm file to serve.
echo ">> inlining wasm into pkg/rust_ffi.js"
node - pkg/rust_ffi.js pkg/rust_ffi_bg.wasm <<'NODE'
const fs = require('fs');
const [, , jsPath, wasmPath] = process.argv;
const b64 = fs.readFileSync(wasmPath).toString('base64');
let src = fs.readFileSync(jsPath, 'utf8');
const needle = /new URL\(['"]rust_ffi_bg\.wasm['"], import\.meta\.url\)/;
if (!needle.test(src)) {
  console.error('inline-wasm: could not find the wasm URL in the glue (wasm-bindgen output changed)');
  process.exit(1);
}
const prelude =
  `const __WASM_B64 = "${b64}";\n` +
  `function __wasmBytes(){const s=atob(__WASM_B64),u=new Uint8Array(s.length);` +
  `for(let i=0;i<s.length;i++)u[i]=s.charCodeAt(i);return u;}\n`;
src = prelude + src.replace(needle, '__wasmBytes()');
fs.writeFileSync(jsPath, src);
console.log(`inline-wasm: embedded ${b64.length} base64 chars`);
NODE
rm -f pkg/rust_ffi_bg.wasm

# Embed the self-contained rust_ffi.js into the KMP web source tree as a base64
# Kotlin constant, so the module ships INSIDE the published klib — no npm, no
# local path. RustFfi.kt decodes it at runtime (Blob URL + import() + init()).
echo ">> writing RustFfiBundle.kt"
BUNDLE="$ROOT/Kmp/api/src/webMain/kotlin/market/femi/api/RustFfiBundle.kt"
mkdir -p "$(dirname "$BUNDLE")"
{
  printf 'package market.femi.api\n\n'
  printf '// Generated by build-rust.sh — base64 of the wasm-inlined rust_ffi.js. Do not edit.\n'
  printf 'internal val RUST_FFI_JS_B64: String =\n    "'
  base64 < pkg/rust_ffi.js | tr -d '\n'
  printf '"\n'
} > "$BUNDLE"

echo
echo "✓ RustFFI.xcframework      → $ROOT/RustFFI.xcframework"
echo "✓ android jniLibs          → $JNI_LIBS"
echo "✓ wasm-bindgen pkg         → $ROOT/Rust/pkg (wasm inlined, self-contained)"
echo "✓ RustFfiBundle.kt         → $BUNDLE"
