@file:OptIn(kotlin.js.ExperimentalWasmJsInterop::class)

package market.femi.api

import kotlinx.coroutines.await
import kotlin.js.Promise

// No @JsModule / npm. The wasm-inlined rust_ffi.js is embedded in the klib as
// base64 (RUST_FFI_JS_B64, generated by build-rust.sh). On first use it is
// turned into an ES module at runtime (Blob URL + dynamic import), init()-ed
// once, and cached. Call `rustFfi()` (suspend) to get the ready module.

external interface RustFfiModule : JsAny {
    fun wasm_z_image_turbo(user: String, pass: String, prompt: String): Promise<JsAny?>
    fun wasm_nano_banana2(user: String, pass: String, prompt: String): Promise<JsAny?>
    fun wasm_flux2_pro(user: String, pass: String, prompt: String): Promise<JsAny?>
    fun wasm_flux2_dev_i2i(user: String, pass: String, imageB64: String, prompt: String): Promise<JsAny?>
    fun wasm_flux2_klein_i2i(user: String, pass: String, imageB64: String, image2B64: String, prompt: String): Promise<JsAny?>
    fun wasm_ltx2_3a2v(user: String, pass: String, imageB64: String, audioB64: String, prompt: String): Promise<JsAny?>
    fun wasm_qwen3_asr_flash(user: String, pass: String, audioB64: String): Promise<JsString>
    fun wasm_qwen3_6_35b_a3b(user: String, pass: String, messagesJson: String): Promise<JsString>
    fun extract_sylt(bytes: JsAny): JsString
    fun psxmp_save_file(name: String, bytes: JsAny, prompt: String?, model: String?, subjects: JsAny): Promise<JsAny?>
    fun psxmp_save_audio(name: String, bytes: JsAny): Promise<JsAny?>
    fun psxmp_like(file: String, liked: Boolean): Promise<JsAny?>
    fun psxmp_get_all_generations(): Promise<JsString>
    fun psxmp_get_audio(): Promise<JsString?>
    fun psxmp_get_prompt(file: String): Promise<JsString?>
    fun psxmp_get_model(file: String): Promise<JsString?>
    fun psxmp_get_subject(file: String): Promise<JsString?>
    fun psxmp_get_like(file: String): Promise<JsBoolean>
    fun psxmp_set_character_cast(a: String, b: String)
    fun psxmp_get_character_cast(): JsString?
    fun psxmp_clear_character_cast()
    fun psxmp_set_image_edit(file: String)
    fun psxmp_get_image_edit(): JsString?
    fun psxmp_clear_image_edit()
}

private var cached: Promise<RustFfiModule>? = null

/** The loaded + initialized Rust FFI wasm module. Loads once, then cached. */
suspend fun rustFfi(): RustFfiModule {
    val p = cached ?: loadRustFfi(RUST_FFI_JS_B64).also { cached = it }
    return p.await()
}

// Decode the base64 bundle -> Blob ES module -> dynamic import() -> init().
// Promise chaining (no async/await) so it compiles for both js and wasmJs.
private fun loadRustFfi(b64: String): Promise<RustFfiModule> = js("""
(function(){
  var code = atob(b64);
  var url = URL.createObjectURL(new Blob([code], { type: 'text/javascript' }));
  return import(/* webpackIgnore: true */ url).then(function(m){ return m.default().then(function(){ return m; }); });
})()
""")

private fun uint8Length(arr: JsAny): Int = js("arr.length")
private fun uint8Byte(arr: JsAny, index: Int): Byte = js("arr[index]")

internal fun JsAny.uint8ToByteArray(): ByteArray {
    val a = this
    val n = uint8Length(a)
    return ByteArray(n) { uint8Byte(a, it) }
}
