//
// ApiAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Recursively flattens an Encodable into bracket-keyed multipart form fields,
/// matching the wire format expected by serde_qs on the rust server.
private func appendBracket(into params: inout [String: any Sendable], baseName: String, value: Any) {
    func walk(_ prefix: String, _ v: Any) {
        switch v {
        case is NSNull:
            return
        case let arr as [Any]:
            for (i, item) in arr.enumerated() { walk("\(prefix)[\(i)]", item) }
        case let dict as [String: Any]:
            for (k, item) in dict { walk("\(prefix)[\(k)]", item) }
        case let n as NSNumber:
            // distinguish bool from numeric
            if CFGetTypeID(n) == CFBooleanGetTypeID() {
                params[prefix] = n.boolValue ? "true" : "false"
            } else {
                params[prefix] = "\(n)"
            }
        default:
            params[prefix] = "\(v)"
        }
    }
    // Encodable -> JSON -> Foundation tree -> walk
    if let encodable = value as? Encodable,
       let data = try? JSONEncoder().encode(AnyEncodable(encodable)),
       let json = try? JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]) {
        walk(baseName, json)
    } else {
        walk(baseName, value)
    }
}

private struct AnyEncodable: Encodable {
    let inner: Encodable
    init(_ inner: Encodable) { self.inner = inner }
    func encode(to encoder: Encoder) throws { try inner.encode(to: encoder) }
}


open class ApiAPI {

    /**

     - parameter action: (form)  
     - parameter audio: (form) filename of already uploaded audio else default 
     - parameter balance: (form)  
     - parameter credit: (form)  
     - parameter file: (form) filename of result to retrieve 
     - parameter id: (form) uuid v7 
     - parameter image: (form) filename of already uploaded image else default 
     - parameter messages: (form) default value is non-empty array 
     - parameter model: (form)  
     - parameter pay: (form)  
     - parameter pricing: (form)  
     - parameter prompt: (form)  
     - parameter requestId: (form) transient, managed by server 
     - parameter status: (form)  
     - parameter userId: (form)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: API
     */
    open class func api(action: ApiAction, audio: String, balance: Int64, credit: Int64, file: String, id: UUID, image: String, messages: [ApiChatMessage], model: ApiAiModel, pay: ApiPay, pricing: ApiPricing, prompt: String, requestId: String, status: ApiStatus, userId: String, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) async throws(ErrorResponse) -> API {
        return try await apiWithRequestBuilder(action: action, audio: audio, balance: balance, credit: credit, file: file, id: id, image: image, messages: messages, model: model, pay: pay, pricing: pricing, prompt: prompt, requestId: requestId, status: status, userId: userId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter action: (form)  
     - parameter audio: (form) filename of already uploaded audio else default 
     - parameter balance: (form)  
     - parameter credit: (form)  
     - parameter file: (form) filename of result to retrieve 
     - parameter id: (form) uuid v7 
     - parameter image: (form) filename of already uploaded image else default 
     - parameter messages: (form) default value is non-empty array 
     - parameter model: (form)  
     - parameter pay: (form)  
     - parameter pricing: (form)  
     - parameter prompt: (form)  
     - parameter requestId: (form) transient, managed by server 
     - parameter status: (form)  
     - parameter userId: (form)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<API> 
     */
    open class func apiWithRequestBuilder(action: ApiAction, audio: String, balance: Int64, credit: Int64, file: String, id: UUID, image: String, messages: [ApiChatMessage], model: ApiAiModel, pay: ApiPay, pricing: ApiPricing, prompt: String, requestId: String, status: ApiStatus, userId: String, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) -> RequestBuilder<API> {
        let localVariablePath = "/api"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        var localVariableParameters: [String: any Sendable] = [:]
        appendBracket(into: &localVariableParameters, baseName: "action", value: action)
        appendBracket(into: &localVariableParameters, baseName: "audio", value: audio)
        appendBracket(into: &localVariableParameters, baseName: "balance", value: balance)
        appendBracket(into: &localVariableParameters, baseName: "credit", value: credit)
        appendBracket(into: &localVariableParameters, baseName: "file", value: file)
        appendBracket(into: &localVariableParameters, baseName: "id", value: id)
        appendBracket(into: &localVariableParameters, baseName: "image", value: image)
        appendBracket(into: &localVariableParameters, baseName: "messages", value: messages)
        appendBracket(into: &localVariableParameters, baseName: "model", value: model)
        appendBracket(into: &localVariableParameters, baseName: "pay", value: pay)
        appendBracket(into: &localVariableParameters, baseName: "pricing", value: pricing)
        appendBracket(into: &localVariableParameters, baseName: "prompt", value: prompt)
        appendBracket(into: &localVariableParameters, baseName: "request_id", value: requestId)
        appendBracket(into: &localVariableParameters, baseName: "status", value: status)
        appendBracket(into: &localVariableParameters, baseName: "user_id", value: userId)
        

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<API>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Auth + per-GB debit gate in front of the `_upload` ServeDir on femi.market.   - not a media file → pass through (static site, app data, 404), free   - media file that isn't a real file in `_upload` → pass through, free   - media file in `_upload` → require Bearer, charge `size × pricing.gb`,     record a debit in the astc ledger, then let ServeDir stream the bytes. The gate only authorizes/charges; ServeDir still does the actual file streaming (range requests, mime, etc.).
     
     - parameter file: (path) media filename in _upload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [Int]
     */
    open class func mediaGate(file: String, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) async throws(ErrorResponse) -> [Int] {
        return try await mediaGateWithRequestBuilder(file: file, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Auth + per-GB debit gate in front of the `_upload` ServeDir on femi.market.   - not a media file → pass through (static site, app data, 404), free   - media file that isn't a real file in `_upload` → pass through, free   - media file in `_upload` → require Bearer, charge `size × pricing.gb`,     record a debit in the astc ledger, then let ServeDir stream the bytes. The gate only authorizes/charges; ServeDir still does the actual file streaming (range requests, mime, etc.).
     - GET /{file}
     - `#[utoipa::path]` here is doc-only — the fn runs as `from_fn` middleware, not a route handler, but the attribute still emits the spec entry so the generated clients get a typed `downloadMedia(file)`. `servers(...)` pins it to femi.market (the global server is api.earnfemi.com); `Request`/`Next` args aren't documentable extractors so utoipa ignores them and uses the explicit `params`.
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter file: (path) media filename in _upload 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[Int]> 
     */
    open class func mediaGateWithRequestBuilder(file: String, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) -> RequestBuilder<[Int]> {
        var localVariablePath = "/{file}"
        let filePreEscape = "\(APIHelper.mapValueToPathItem(file))"
        let filePostEscape = filePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{file}", with: filePostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[Int]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
