//
// ApiKeyRouteAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Recursively flattens an Encodable into bracket-keyed multipart form fields,
/// matching the wire format expected by serde_qs on the rust server.
private func appendBracket(into params: inout [String: any Sendable], baseName: String, value: Any) {
    func walk(_ prefix: String, _ v: Any) {
        switch v {
        case is NSNull:
            return
        case let arr as [Any]:
            for (i, item) in arr.enumerated() { walk("\(prefix)[\(i)]", item) }
        case let dict as [String: Any]:
            for (k, item) in dict { walk("\(prefix)[\(k)]", item) }
        case let n as NSNumber:
            // distinguish bool from numeric
            if CFGetTypeID(n) == CFBooleanGetTypeID() {
                params[prefix] = n.boolValue ? "true" : "false"
            } else {
                params[prefix] = "\(n)"
            }
        default:
            params[prefix] = "\(v)"
        }
    }
    // Encodable -> JSON -> Foundation tree -> walk
    if let encodable = value as? Encodable,
       let data = try? JSONEncoder().encode(AnyEncodable(encodable)),
       let json = try? JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]) {
        walk(baseName, json)
    } else {
        walk(baseName, value)
    }
}

private struct AnyEncodable: Encodable {
    let inner: Encodable
    init(_ inner: Encodable) { self.inner = inner }
    func encode(to encoder: Encoder) throws { try inner.encode(to: encoder) }
}


open class ApiKeyRouteAPI {

    /**

     - parameter id: (form)  
     - parameter userId: (form)  
     - parameter key: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ApiKey
     */
    open class func apiKey(id: UUID, userId: String, key: String? = nil, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) async throws(ErrorResponse) -> ApiKey {
        return try await apiKeyWithRequestBuilder(id: id, userId: userId, key: key, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /api_key
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter id: (form)  
     - parameter userId: (form)  
     - parameter key: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ApiKey> 
     */
    open class func apiKeyWithRequestBuilder(id: UUID, userId: String, key: String? = nil, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) -> RequestBuilder<ApiKey> {
        let localVariablePath = "/api_key"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        var localVariableParameters: [String: any Sendable] = [:]
        appendBracket(into: &localVariableParameters, baseName: "id", value: id)
        if let value = key { appendBracket(into: &localVariableParameters, baseName: "key", value: value) }
        appendBracket(into: &localVariableParameters, baseName: "user_id", value: userId)
        

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiKey>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
