//
// ApplePayRouteAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Recursively flattens an Encodable into bracket-keyed multipart form fields,
/// matching the wire format expected by serde_qs on the rust server.
private func appendBracket(into params: inout [String: any Sendable], baseName: String, value: Any) {
    func walk(_ prefix: String, _ v: Any) {
        switch v {
        case is NSNull:
            return
        case let arr as [Any]:
            for (i, item) in arr.enumerated() { walk("\(prefix)[\(i)]", item) }
        case let dict as [String: Any]:
            for (k, item) in dict { walk("\(prefix)[\(k)]", item) }
        case let n as NSNumber:
            // distinguish bool from numeric
            if CFGetTypeID(n) == CFBooleanGetTypeID() {
                params[prefix] = n.boolValue ? "true" : "false"
            } else {
                params[prefix] = "\(n)"
            }
        default:
            params[prefix] = "\(v)"
        }
    }
    // Encodable -> JSON -> Foundation tree -> walk
    if let encodable = value as? Encodable,
       let data = try? JSONEncoder().encode(AnyEncodable(encodable)),
       let json = try? JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]) {
        walk(baseName, json)
    } else {
        walk(baseName, value)
    }
}

private struct AnyEncodable: Encodable {
    let inner: Encodable
    init(_ inner: Encodable) { self.inner = inner }
    func encode(to encoder: Encoder) throws { try inner.encode(to: encoder) }
}


open class ApplePayRouteAPI {

    /**

     - parameter credit: (form)  
     - parameter currency: (form)  
     - parameter id: (form) uuid v7 
     - parameter jws: (form)  
     - parameter loaded: (form)  
     - parameter price: (form)  
     - parameter productId: (form)  
     - parameter status: (form)  
     - parameter transactionId: (form)  
     - parameter userId: (form)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ApplePay
     */
    open class func applePay(credit: Int64, currency: String, id: UUID, jws: String, loaded: Bool, price: Int64, productId: String, status: ApplePayStatus, transactionId: String, userId: String, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) async throws(ErrorResponse) -> ApplePay {
        return try await applePayWithRequestBuilder(credit: credit, currency: currency, id: id, jws: jws, loaded: loaded, price: price, productId: productId, status: status, transactionId: transactionId, userId: userId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /apple_pay
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter credit: (form)  
     - parameter currency: (form)  
     - parameter id: (form) uuid v7 
     - parameter jws: (form)  
     - parameter loaded: (form)  
     - parameter price: (form)  
     - parameter productId: (form)  
     - parameter status: (form)  
     - parameter transactionId: (form)  
     - parameter userId: (form)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ApplePay> 
     */
    open class func applePayWithRequestBuilder(credit: Int64, currency: String, id: UUID, jws: String, loaded: Bool, price: Int64, productId: String, status: ApplePayStatus, transactionId: String, userId: String, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) -> RequestBuilder<ApplePay> {
        let localVariablePath = "/apple_pay"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        var localVariableParameters: [String: any Sendable] = [:]
        appendBracket(into: &localVariableParameters, baseName: "credit", value: credit)
        appendBracket(into: &localVariableParameters, baseName: "currency", value: currency)
        appendBracket(into: &localVariableParameters, baseName: "id", value: id)
        appendBracket(into: &localVariableParameters, baseName: "jws", value: jws)
        appendBracket(into: &localVariableParameters, baseName: "loaded", value: loaded)
        appendBracket(into: &localVariableParameters, baseName: "price", value: price)
        appendBracket(into: &localVariableParameters, baseName: "product_id", value: productId)
        appendBracket(into: &localVariableParameters, baseName: "status", value: status)
        appendBracket(into: &localVariableParameters, baseName: "transaction_id", value: transactionId)
        appendBracket(into: &localVariableParameters, baseName: "user_id", value: userId)
        

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApplePay>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
