//
// LyricSyncRouteAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Recursively flattens an Encodable into bracket-keyed multipart form fields,
/// matching the wire format expected by serde_qs on the rust server.
private func appendBracket(into params: inout [String: any Sendable], baseName: String, value: Any) {
    func walk(_ prefix: String, _ v: Any) {
        switch v {
        case is NSNull:
            return
        case let arr as [Any]:
            for (i, item) in arr.enumerated() { walk("\(prefix)[\(i)]", item) }
        case let dict as [String: Any]:
            for (k, item) in dict { walk("\(prefix)[\(k)]", item) }
        case let n as NSNumber:
            // distinguish bool from numeric
            if CFGetTypeID(n) == CFBooleanGetTypeID() {
                params[prefix] = n.boolValue ? "true" : "false"
            } else {
                params[prefix] = "\(n)"
            }
        default:
            params[prefix] = "\(v)"
        }
    }
    // Encodable -> JSON -> Foundation tree -> walk
    if let encodable = value as? Encodable,
       let data = try? JSONEncoder().encode(AnyEncodable(encodable)),
       let json = try? JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]) {
        walk(baseName, json)
    } else {
        walk(baseName, value)
    }
}

private struct AnyEncodable: Encodable {
    let inner: Encodable
    init(_ inner: Encodable) { self.inner = inner }
    func encode(to encoder: Encoder) throws { try inner.encode(to: encoder) }
}


open class LyricSyncRouteAPI {

    /**

     - parameter audio: (form)  
     - parameter id: (form)  
     - parameter lyrics: (form)  
     - parameter characters: (form)  (optional)
     - parameter credit: (form)  (optional)
     - parameter loss: (form)  (optional)
     - parameter userId: (form)  (optional)
     - parameter words: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: LyricSync
     */
    open class func lyricSync(audio: String, id: UUID, lyrics: String, characters: [CharacterAlignment]? = nil, credit: Int64? = nil, loss: Double? = nil, userId: String? = nil, words: [WordAlignment]? = nil, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) async throws(ErrorResponse) -> LyricSync {
        return try await lyricSyncWithRequestBuilder(audio: audio, id: id, lyrics: lyrics, characters: characters, credit: credit, loss: loss, userId: userId, words: words, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /lyric_sync
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter audio: (form)  
     - parameter id: (form)  
     - parameter lyrics: (form)  
     - parameter characters: (form)  (optional)
     - parameter credit: (form)  (optional)
     - parameter loss: (form)  (optional)
     - parameter userId: (form)  (optional)
     - parameter words: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<LyricSync> 
     */
    open class func lyricSyncWithRequestBuilder(audio: String, id: UUID, lyrics: String, characters: [CharacterAlignment]? = nil, credit: Int64? = nil, loss: Double? = nil, userId: String? = nil, words: [WordAlignment]? = nil, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) -> RequestBuilder<LyricSync> {
        let localVariablePath = "/lyric_sync"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        var localVariableParameters: [String: any Sendable] = [:]
        appendBracket(into: &localVariableParameters, baseName: "audio", value: audio)
        if let value = characters { appendBracket(into: &localVariableParameters, baseName: "characters", value: value) }
        if let value = credit { appendBracket(into: &localVariableParameters, baseName: "credit", value: value) }
        appendBracket(into: &localVariableParameters, baseName: "id", value: id)
        if let value = loss { appendBracket(into: &localVariableParameters, baseName: "loss", value: value) }
        appendBracket(into: &localVariableParameters, baseName: "lyrics", value: lyrics)
        if let value = userId { appendBracket(into: &localVariableParameters, baseName: "user_id", value: value) }
        if let value = words { appendBracket(into: &localVariableParameters, baseName: "words", value: value) }
        

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LyricSync>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
