//
// PayRouteAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Recursively flattens an Encodable into bracket-keyed multipart form fields,
/// matching the wire format expected by serde_qs on the rust server.
private func appendBracket(into params: inout [String: any Sendable], baseName: String, value: Any) {
    func walk(_ prefix: String, _ v: Any) {
        switch v {
        case is NSNull:
            return
        case let arr as [Any]:
            for (i, item) in arr.enumerated() { walk("\(prefix)[\(i)]", item) }
        case let dict as [String: Any]:
            for (k, item) in dict { walk("\(prefix)[\(k)]", item) }
        case let n as NSNumber:
            // distinguish bool from numeric
            if CFGetTypeID(n) == CFBooleanGetTypeID() {
                params[prefix] = n.boolValue ? "true" : "false"
            } else {
                params[prefix] = "\(n)"
            }
        default:
            params[prefix] = "\(v)"
        }
    }
    // Encodable -> JSON -> Foundation tree -> walk
    if let encodable = value as? Encodable,
       let data = try? JSONEncoder().encode(AnyEncodable(encodable)),
       let json = try? JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]) {
        walk(baseName, json)
    } else {
        walk(baseName, value)
    }
}

private struct AnyEncodable: Encodable {
    let inner: Encodable
    init(_ inner: Encodable) { self.inner = inner }
    func encode(to encoder: Encoder) throws { try inner.encode(to: encoder) }
}


open class PayRouteAPI {

    /**

     - parameter id: (form) uuid v7 
     - parameter provider: (form) Selects the verification path: Apple App Store vs Google Play. 
     - parameter userId: (form)  
     - parameter credit: (form)  (optional)
     - parameter currency: (form)  (optional)
     - parameter jws: (form) Signed transaction JWS from StoreKit; the input to Apple verification. (optional)
     - parameter loaded: (form)  (optional)
     - parameter orderId: (form) Google&#39;s per-purchase &#x60;orderId&#x60;, returned by the Play Developer API (not the client). Not used for dedup — &#x60;ref_id&#x60; is — because promo-code purchases may have no &#x60;orderId&#x60;. (optional)
     - parameter packageName: (form)  (optional)
     - parameter price: (form)  (optional)
     - parameter productId: (form)  (optional)
     - parameter refId: (form) Globally-unique purchase id, used as the idempotency key for both stores. Apple: the &#x60;transactionId&#x60;, extracted server-side from the verified JWS   (empty on the incoming request — the server fills it in). Google: the &#x60;purchaseToken&#x60;, sent by the client. It is both the input to   Play Developer API verification and the idempotency key. (optional)
     - parameter status: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Pay
     */
    open class func pay(id: UUID, provider: PayProvider, userId: String, credit: Int64? = nil, currency: String? = nil, jws: String? = nil, loaded: Bool? = nil, orderId: String? = nil, packageName: String? = nil, price: Int64? = nil, productId: String? = nil, refId: String? = nil, status: PayStatus? = nil, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) async throws(ErrorResponse) -> Pay {
        return try await payWithRequestBuilder(id: id, provider: provider, userId: userId, credit: credit, currency: currency, jws: jws, loaded: loaded, orderId: orderId, packageName: packageName, price: price, productId: productId, refId: refId, status: status, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /pay
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter id: (form) uuid v7 
     - parameter provider: (form) Selects the verification path: Apple App Store vs Google Play. 
     - parameter userId: (form)  
     - parameter credit: (form)  (optional)
     - parameter currency: (form)  (optional)
     - parameter jws: (form) Signed transaction JWS from StoreKit; the input to Apple verification. (optional)
     - parameter loaded: (form)  (optional)
     - parameter orderId: (form) Google&#39;s per-purchase &#x60;orderId&#x60;, returned by the Play Developer API (not the client). Not used for dedup — &#x60;ref_id&#x60; is — because promo-code purchases may have no &#x60;orderId&#x60;. (optional)
     - parameter packageName: (form)  (optional)
     - parameter price: (form)  (optional)
     - parameter productId: (form)  (optional)
     - parameter refId: (form) Globally-unique purchase id, used as the idempotency key for both stores. Apple: the &#x60;transactionId&#x60;, extracted server-side from the verified JWS   (empty on the incoming request — the server fills it in). Google: the &#x60;purchaseToken&#x60;, sent by the client. It is both the input to   Play Developer API verification and the idempotency key. (optional)
     - parameter status: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Pay> 
     */
    open class func payWithRequestBuilder(id: UUID, provider: PayProvider, userId: String, credit: Int64? = nil, currency: String? = nil, jws: String? = nil, loaded: Bool? = nil, orderId: String? = nil, packageName: String? = nil, price: Int64? = nil, productId: String? = nil, refId: String? = nil, status: PayStatus? = nil, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) -> RequestBuilder<Pay> {
        let localVariablePath = "/pay"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        var localVariableParameters: [String: any Sendable] = [:]
        if let value = credit { appendBracket(into: &localVariableParameters, baseName: "credit", value: value) }
        if let value = currency { appendBracket(into: &localVariableParameters, baseName: "currency", value: value) }
        appendBracket(into: &localVariableParameters, baseName: "id", value: id)
        if let value = jws { appendBracket(into: &localVariableParameters, baseName: "jws", value: value) }
        if let value = loaded { appendBracket(into: &localVariableParameters, baseName: "loaded", value: value) }
        if let value = orderId { appendBracket(into: &localVariableParameters, baseName: "order_id", value: value) }
        if let value = packageName { appendBracket(into: &localVariableParameters, baseName: "package_name", value: value) }
        if let value = price { appendBracket(into: &localVariableParameters, baseName: "price", value: value) }
        if let value = productId { appendBracket(into: &localVariableParameters, baseName: "product_id", value: value) }
        appendBracket(into: &localVariableParameters, baseName: "provider", value: provider)
        if let value = refId { appendBracket(into: &localVariableParameters, baseName: "ref_id", value: value) }
        if let value = status { appendBracket(into: &localVariableParameters, baseName: "status", value: value) }
        appendBracket(into: &localVariableParameters, baseName: "user_id", value: userId)
        

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Pay>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
