//
// ProjectRouteAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Recursively flattens an Encodable into bracket-keyed multipart form fields,
/// matching the wire format expected by serde_qs on the rust server.
private func appendBracket(into params: inout [String: any Sendable], baseName: String, value: Any) {
    func walk(_ prefix: String, _ v: Any) {
        switch v {
        case is NSNull:
            return
        case let arr as [Any]:
            for (i, item) in arr.enumerated() { walk("\(prefix)[\(i)]", item) }
        case let dict as [String: Any]:
            for (k, item) in dict { walk("\(prefix)[\(k)]", item) }
        case let n as NSNumber:
            // distinguish bool from numeric
            if CFGetTypeID(n) == CFBooleanGetTypeID() {
                params[prefix] = n.boolValue ? "true" : "false"
            } else {
                params[prefix] = "\(n)"
            }
        default:
            params[prefix] = "\(v)"
        }
    }
    // Encodable -> JSON -> Foundation tree -> walk
    if let encodable = value as? Encodable,
       let data = try? JSONEncoder().encode(AnyEncodable(encodable)),
       let json = try? JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]) {
        walk(baseName, json)
    } else {
        walk(baseName, value)
    }
}

private struct AnyEncodable: Encodable {
    let inner: Encodable
    init(_ inner: Encodable) { self.inner = inner }
    func encode(to encoder: Encoder) throws { try inner.encode(to: encoder) }
}


open class ProjectRouteAPI {

    /**

     - parameter about: (form)  
     - parameter audio: (form)  
     - parameter audioLines: (form)  
     - parameter faqs: (form)  
     - parameter genre: (form)  
     - parameter id: (form)  
     - parameter playlist: (form)  
     - parameter seasons: (form)  
     - parameter summary: (form)  
     - parameter userId: (form)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Project
     */
    open class func project(about: String, audio: String, audioLines: [AudioLine], faqs: [Faq], genre: String, id: UUID, playlist: String, seasons: [Season], summary: String, userId: String, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) async throws(ErrorResponse) -> Project {
        return try await projectWithRequestBuilder(about: about, audio: audio, audioLines: audioLines, faqs: faqs, genre: genre, id: id, playlist: playlist, seasons: seasons, summary: summary, userId: userId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /project
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter about: (form)  
     - parameter audio: (form)  
     - parameter audioLines: (form)  
     - parameter faqs: (form)  
     - parameter genre: (form)  
     - parameter id: (form)  
     - parameter playlist: (form)  
     - parameter seasons: (form)  
     - parameter summary: (form)  
     - parameter userId: (form)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Project> 
     */
    open class func projectWithRequestBuilder(about: String, audio: String, audioLines: [AudioLine], faqs: [Faq], genre: String, id: UUID, playlist: String, seasons: [Season], summary: String, userId: String, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) -> RequestBuilder<Project> {
        let localVariablePath = "/project"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        var localVariableParameters: [String: any Sendable] = [:]
        appendBracket(into: &localVariableParameters, baseName: "about", value: about)
        appendBracket(into: &localVariableParameters, baseName: "audio", value: audio)
        appendBracket(into: &localVariableParameters, baseName: "audio_lines", value: audioLines)
        appendBracket(into: &localVariableParameters, baseName: "faqs", value: faqs)
        appendBracket(into: &localVariableParameters, baseName: "genre", value: genre)
        appendBracket(into: &localVariableParameters, baseName: "id", value: id)
        appendBracket(into: &localVariableParameters, baseName: "playlist", value: playlist)
        appendBracket(into: &localVariableParameters, baseName: "seasons", value: seasons)
        appendBracket(into: &localVariableParameters, baseName: "summary", value: summary)
        appendBracket(into: &localVariableParameters, baseName: "user_id", value: userId)
        

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Project>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
