//
// SolanaRouteAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Recursively flattens an Encodable into bracket-keyed multipart form fields,
/// matching the wire format expected by serde_qs on the rust server.
private func appendBracket(into params: inout [String: any Sendable], baseName: String, value: Any) {
    func walk(_ prefix: String, _ v: Any) {
        switch v {
        case is NSNull:
            return
        case let arr as [Any]:
            for (i, item) in arr.enumerated() { walk("\(prefix)[\(i)]", item) }
        case let dict as [String: Any]:
            for (k, item) in dict { walk("\(prefix)[\(k)]", item) }
        case let n as NSNumber:
            // distinguish bool from numeric
            if CFGetTypeID(n) == CFBooleanGetTypeID() {
                params[prefix] = n.boolValue ? "true" : "false"
            } else {
                params[prefix] = "\(n)"
            }
        default:
            params[prefix] = "\(v)"
        }
    }
    // Encodable -> JSON -> Foundation tree -> walk
    if let encodable = value as? Encodable,
       let data = try? JSONEncoder().encode(AnyEncodable(encodable)),
       let json = try? JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]) {
        walk(baseName, json)
    } else {
        walk(baseName, value)
    }
}

private struct AnyEncodable: Encodable {
    let inner: Encodable
    init(_ inner: Encodable) { self.inner = inner }
    func encode(to encoder: Encoder) throws { try inner.encode(to: encoder) }
}


open class SolanaRouteAPI {

    /**

     - parameter amountCents: (form)  
     - parameter id: (form)  
     - parameter pubkey: (form)  
     - parameter status: (form)  
     - parameter userId: (form)  
     - parameter credit: (form)  (optional)
     - parameter loaded: (form)  (optional)
     - parameter quotedOutUnits: (form)  (optional)
     - parameter requestId: (form)  (optional)
     - parameter signature: (form)  (optional)
     - parameter signedTx: (form)  (optional)
     - parameter unsignedTx: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Solana
     */
    open class func solana(amountCents: Int64, id: UUID, pubkey: String, status: Status, userId: String, credit: Int64? = nil, loaded: Bool? = nil, quotedOutUnits: Int64? = nil, requestId: String? = nil, signature: String? = nil, signedTx: String? = nil, unsignedTx: String? = nil, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) async throws(ErrorResponse) -> Solana {
        return try await solanaWithRequestBuilder(amountCents: amountCents, id: id, pubkey: pubkey, status: status, userId: userId, credit: credit, loaded: loaded, quotedOutUnits: quotedOutUnits, requestId: requestId, signature: signature, signedTx: signedTx, unsignedTx: unsignedTx, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /solana
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter amountCents: (form)  
     - parameter id: (form)  
     - parameter pubkey: (form)  
     - parameter status: (form)  
     - parameter userId: (form)  
     - parameter credit: (form)  (optional)
     - parameter loaded: (form)  (optional)
     - parameter quotedOutUnits: (form)  (optional)
     - parameter requestId: (form)  (optional)
     - parameter signature: (form)  (optional)
     - parameter signedTx: (form)  (optional)
     - parameter unsignedTx: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Solana> 
     */
    open class func solanaWithRequestBuilder(amountCents: Int64, id: UUID, pubkey: String, status: Status, userId: String, credit: Int64? = nil, loaded: Bool? = nil, quotedOutUnits: Int64? = nil, requestId: String? = nil, signature: String? = nil, signedTx: String? = nil, unsignedTx: String? = nil, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) -> RequestBuilder<Solana> {
        let localVariablePath = "/solana"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        var localVariableParameters: [String: any Sendable] = [:]
        appendBracket(into: &localVariableParameters, baseName: "amount_cents", value: amountCents)
        if let value = credit { appendBracket(into: &localVariableParameters, baseName: "credit", value: value) }
        appendBracket(into: &localVariableParameters, baseName: "id", value: id)
        if let value = loaded { appendBracket(into: &localVariableParameters, baseName: "loaded", value: value) }
        appendBracket(into: &localVariableParameters, baseName: "pubkey", value: pubkey)
        if let value = quotedOutUnits { appendBracket(into: &localVariableParameters, baseName: "quoted_out_units", value: value) }
        if let value = requestId { appendBracket(into: &localVariableParameters, baseName: "request_id", value: value) }
        if let value = signature { appendBracket(into: &localVariableParameters, baseName: "signature", value: value) }
        if let value = signedTx { appendBracket(into: &localVariableParameters, baseName: "signed_tx", value: value) }
        appendBracket(into: &localVariableParameters, baseName: "status", value: status)
        if let value = unsignedTx { appendBracket(into: &localVariableParameters, baseName: "unsigned_tx", value: value) }
        appendBracket(into: &localVariableParameters, baseName: "user_id", value: userId)
        

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Solana>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
