//
// WiseRouteAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Recursively flattens an Encodable into bracket-keyed multipart form fields,
/// matching the wire format expected by serde_qs on the rust server.
private func appendBracket(into params: inout [String: any Sendable], baseName: String, value: Any) {
    func walk(_ prefix: String, _ v: Any) {
        switch v {
        case is NSNull:
            return
        case let arr as [Any]:
            for (i, item) in arr.enumerated() { walk("\(prefix)[\(i)]", item) }
        case let dict as [String: Any]:
            for (k, item) in dict { walk("\(prefix)[\(k)]", item) }
        case let n as NSNumber:
            // distinguish bool from numeric
            if CFGetTypeID(n) == CFBooleanGetTypeID() {
                params[prefix] = n.boolValue ? "true" : "false"
            } else {
                params[prefix] = "\(n)"
            }
        default:
            params[prefix] = "\(v)"
        }
    }
    // Encodable -> JSON -> Foundation tree -> walk
    if let encodable = value as? Encodable,
       let data = try? JSONEncoder().encode(AnyEncodable(encodable)),
       let json = try? JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]) {
        walk(baseName, json)
    } else {
        walk(baseName, value)
    }
}

private struct AnyEncodable: Encodable {
    let inner: Encodable
    init(_ inner: Encodable) { self.inner = inner }
    func encode(to encoder: Encoder) throws { try inner.encode(to: encoder) }
}


open class WiseRouteAPI {

    /**

     - parameter amountCents: (form)  
     - parameter currency: (form)  
     - parameter id: (form)  
     - parameter reference: (form)  
     - parameter status: (form)  
     - parameter userId: (form)  
     - parameter credit: (form)  (optional)
     - parameter loaded: (form)  (optional)
     - parameter wiseCreditId: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Wise
     */
    open class func wise(amountCents: Int64, currency: String, id: UUID, reference: String, status: Status, userId: String, credit: Int64? = nil, loaded: Bool? = nil, wiseCreditId: String? = nil, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) async throws(ErrorResponse) -> Wise {
        return try await wiseWithRequestBuilder(amountCents: amountCents, currency: currency, id: id, reference: reference, status: status, userId: userId, credit: credit, loaded: loaded, wiseCreditId: wiseCreditId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /wise
     - Bearer Token:
       - type: http
       - name: bearer
     - parameter amountCents: (form)  
     - parameter currency: (form)  
     - parameter id: (form)  
     - parameter reference: (form)  
     - parameter status: (form)  
     - parameter userId: (form)  
     - parameter credit: (form)  (optional)
     - parameter loaded: (form)  (optional)
     - parameter wiseCreditId: (form)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Wise> 
     */
    open class func wiseWithRequestBuilder(amountCents: Int64, currency: String, id: UUID, reference: String, status: Status, userId: String, credit: Int64? = nil, loaded: Bool? = nil, wiseCreditId: String? = nil, apiConfiguration: ApiAPIConfiguration = ApiAPIConfiguration.shared) -> RequestBuilder<Wise> {
        let localVariablePath = "/wise"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        var localVariableParameters: [String: any Sendable] = [:]
        appendBracket(into: &localVariableParameters, baseName: "amount_cents", value: amountCents)
        if let value = credit { appendBracket(into: &localVariableParameters, baseName: "credit", value: value) }
        appendBracket(into: &localVariableParameters, baseName: "currency", value: currency)
        appendBracket(into: &localVariableParameters, baseName: "id", value: id)
        if let value = loaded { appendBracket(into: &localVariableParameters, baseName: "loaded", value: value) }
        appendBracket(into: &localVariableParameters, baseName: "reference", value: reference)
        appendBracket(into: &localVariableParameters, baseName: "status", value: status)
        appendBracket(into: &localVariableParameters, baseName: "user_id", value: userId)
        if let value = wiseCreditId { appendBracket(into: &localVariableParameters, baseName: "wise_credit_id", value: value) }
        

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Wise>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
