//
// API.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** default values */
public struct API: Sendable, Codable, Hashable {

    public var action: ApiAction
    /** return only */
    public var credit: Int64
    /** uuid v7 preferred */
    public var id: UUID
    public var status: ApiStatus
    public var userId: String

    public init(action: ApiAction, credit: Int64, id: UUID, status: ApiStatus, userId: String) {
        self.action = action
        self.credit = credit
        self.id = id
        self.status = status
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case action
        case credit
        case id
        case status
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(action, forKey: .action)
        try container.encode(credit, forKey: .credit)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
        try container.encode(userId, forKey: .userId)
    }
}


extension API: Identifiable {}
