//
// ApiAiModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ApiAiModel: String, Sendable, Codable, CaseIterable {
    case zimageturbo = "ZImageTurbo"
    case nanoBanana2 = "NanoBanana2"
    case flux2Pro = "Flux2Pro"
    case ltx23a2v = "Ltx2_3A2V"
}
