//
// ApiAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ApiAction: Sendable, Codable, Hashable {
    case typeApplePay(ApplePay)
    case typeCharge(Charge)
    case typeClaudeSonnet46(ClaudeSonnet46)
    case typeFlux2DevI2I(Flux2DevI2I)
    case typeFlux2KleinI2I(Flux2KleinI2I)
    case typeFlux2Pro(Flux2Pro)
    case typeGooglePay(GooglePay)
    case typeLtx23A2V(Ltx23A2V)
    case typeLyricSync(LyricSync)
    case typeNanoBanana2(NanoBanana2)
    case typeStripe(Stripe)
    case typeZImageTurbo(ZImageTurbo)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeApplePay(let value):
            try container.encode(value)
        case .typeCharge(let value):
            try container.encode(value)
        case .typeClaudeSonnet46(let value):
            try container.encode(value)
        case .typeFlux2DevI2I(let value):
            try container.encode(value)
        case .typeFlux2KleinI2I(let value):
            try container.encode(value)
        case .typeFlux2Pro(let value):
            try container.encode(value)
        case .typeGooglePay(let value):
            try container.encode(value)
        case .typeLtx23A2V(let value):
            try container.encode(value)
        case .typeLyricSync(let value):
            try container.encode(value)
        case .typeNanoBanana2(let value):
            try container.encode(value)
        case .typeStripe(let value):
            try container.encode(value)
        case .typeZImageTurbo(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case type = "type"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .type)

        switch discriminatorValue {
        case "ApplePay":
            self = .typeApplePay(try ApplePay(from: decoder))
        case "Charge":
            self = .typeCharge(try Charge(from: decoder))
        case "ClaudeSonnet4_6":
            self = .typeClaudeSonnet46(try ClaudeSonnet46(from: decoder))
        case "Flux2DevI2I":
            self = .typeFlux2DevI2I(try Flux2DevI2I(from: decoder))
        case "Flux2KleinI2I":
            self = .typeFlux2KleinI2I(try Flux2KleinI2I(from: decoder))
        case "Flux2Pro":
            self = .typeFlux2Pro(try Flux2Pro(from: decoder))
        case "GooglePay":
            self = .typeGooglePay(try GooglePay(from: decoder))
        case "Ltx2_3A2V":
            self = .typeLtx23A2V(try Ltx23A2V(from: decoder))
        case "LyricSync":
            self = .typeLyricSync(try LyricSync(from: decoder))
        case "NanoBanana2":
            self = .typeNanoBanana2(try NanoBanana2(from: decoder))
        case "Stripe":
            self = .typeStripe(try Stripe(from: decoder))
        case "ZImageTurbo":
            self = .typeZImageTurbo(try ZImageTurbo(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for ApiAction"
                )
            )
        }
    }
}

