//
// ApiAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ApiAction: String, Sendable, Codable, CaseIterable {
    case generate = "Generate"
    case pay = "Pay"
}
