//
// ApiChatMessage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiChatMessage: Sendable, Codable, Hashable {

    public var content: String
    public var role: ApiChatRole

    public init(content: String, role: ApiChatRole) {
        self.content = content
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case content
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(content, forKey: .content)
        try container.encode(role, forKey: .role)
    }
}

