//
// ApiChatRole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ApiChatRole: String, Sendable, Codable, CaseIterable {
    case user = "User"
    case assistant = "Assistant"
}
