//
// ApiKey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiKey: Sendable, Codable, Hashable {

    public var id: UUID
    public var key: String?
    public var userId: String

    public init(id: UUID, key: String? = nil, userId: String) {
        self.id = id
        self.key = key
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case key
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(key, forKey: .key)
        try container.encode(userId, forKey: .userId)
    }
}


extension ApiKey: Identifiable {}
