//
// ApiPayProvider.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ApiPayProvider: String, Sendable, Codable, CaseIterable {
    case apple = "Apple"
    case google = "Google"
}
