//
// ApiPay.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** default values */
public struct ApiPay: Sendable, Codable, Hashable {

    public var currency: String
    /** uuid v7 */
    public var id: UUID
    /** Signed transaction JWS from StoreKit; the input to Apple verification. */
    public var jws: String
    public var loaded: Bool
    /** Google's per-purchase `orderId`, returned by the Play Developer API (not the client). Not used for dedup — `ref_id` is — because promo-code purchases may have no `orderId`. */
    public var orderId: String?
    public var packageName: String
    public var price: Int64
    public var productId: String
    /** Selects the verification path: Apple App Store vs Google Play. */
    public var provider: ApiPayProvider
    /** Globally-unique purchase id, used as the idempotency key for both stores. Apple: the `transactionId`, extracted server-side from the verified JWS   (empty on the incoming request — the server fills it in). Google: the `purchaseToken`, sent by the client. It is both the input to   Play Developer API verification and the idempotency key. */
    public var refId: String
    public var userId: String

    public init(currency: String, id: UUID, jws: String, loaded: Bool, orderId: String? = nil, packageName: String, price: Int64, productId: String, provider: ApiPayProvider, refId: String, userId: String) {
        self.currency = currency
        self.id = id
        self.jws = jws
        self.loaded = loaded
        self.orderId = orderId
        self.packageName = packageName
        self.price = price
        self.productId = productId
        self.provider = provider
        self.refId = refId
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currency
        case id
        case jws
        case loaded
        case orderId = "order_id"
        case packageName = "package_name"
        case price
        case productId = "product_id"
        case provider
        case refId = "ref_id"
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(currency, forKey: .currency)
        try container.encode(id, forKey: .id)
        try container.encode(jws, forKey: .jws)
        try container.encode(loaded, forKey: .loaded)
        try container.encodeIfPresent(orderId, forKey: .orderId)
        try container.encode(packageName, forKey: .packageName)
        try container.encode(price, forKey: .price)
        try container.encode(productId, forKey: .productId)
        try container.encode(provider, forKey: .provider)
        try container.encode(refId, forKey: .refId)
        try container.encode(userId, forKey: .userId)
    }
}


extension ApiPay: Identifiable {}
