//
// ApplePayStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ApplePayStatus: String, Sendable, Codable, CaseIterable {
    case pending = "Pending"
    case completed = "Completed"
    case failed = "Failed"
}
