//
// ApplePay.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Put default values */
public struct ApplePay: Sendable, Codable, Hashable {

    public var credit: Int64
    public var currency: String
    /** uuid v7 */
    public var id: UUID
    public var jws: String
    public var loaded: Bool
    public var price: Int64
    public var productId: String
    public var status: ApplePayStatus
    public var transactionId: String
    public var userId: String

    public init(credit: Int64, currency: String, id: UUID, jws: String, loaded: Bool, price: Int64, productId: String, status: ApplePayStatus, transactionId: String, userId: String) {
        self.credit = credit
        self.currency = currency
        self.id = id
        self.jws = jws
        self.loaded = loaded
        self.price = price
        self.productId = productId
        self.status = status
        self.transactionId = transactionId
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case credit
        case currency
        case id
        case jws
        case loaded
        case price
        case productId = "product_id"
        case status
        case transactionId = "transaction_id"
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(credit, forKey: .credit)
        try container.encode(currency, forKey: .currency)
        try container.encode(id, forKey: .id)
        try container.encode(jws, forKey: .jws)
        try container.encode(loaded, forKey: .loaded)
        try container.encode(price, forKey: .price)
        try container.encode(productId, forKey: .productId)
        try container.encode(status, forKey: .status)
        try container.encode(transactionId, forKey: .transactionId)
        try container.encode(userId, forKey: .userId)
    }
}


extension ApplePay: Identifiable {}
