//
// AudioLine.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AudioLine: Sendable, Codable, Hashable {

    public var context: String
    public var goal: String
    public var id: UUID
    public var line: String
    public var startTime: Double

    public init(context: String, goal: String, id: UUID, line: String, startTime: Double) {
        self.context = context
        self.goal = goal
        self.id = id
        self.line = line
        self.startTime = startTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case context
        case goal
        case id
        case line
        case startTime = "start_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(context, forKey: .context)
        try container.encode(goal, forKey: .goal)
        try container.encode(id, forKey: .id)
        try container.encode(line, forKey: .line)
        try container.encode(startTime, forKey: .startTime)
    }
}


extension AudioLine: Identifiable {}
