//
// Charge.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Charge: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case charge = "Charge"
    }
    public var description: String
    public var type: ModelType

    public init(description: String, type: ModelType) {
        self.description = description
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(description, forKey: .description)
        try container.encode(type, forKey: .type)
    }
}

