//
// Episode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Episode: Sendable, Codable, Hashable {

    public var id: UUID
    public var scenes: [Scene]

    public init(id: UUID, scenes: [Scene]) {
        self.id = id
        self.scenes = scenes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case scenes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(scenes, forKey: .scenes)
    }
}


extension Episode: Identifiable {}
