//
// Faq.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Faq: Sendable, Codable, Hashable {

    public var answer: String
    public var id: UUID
    public var question: String

    public init(answer: String, id: UUID, question: String) {
        self.answer = answer
        self.id = id
        self.question = question
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case answer
        case id
        case question
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(answer, forKey: .answer)
        try container.encode(id, forKey: .id)
        try container.encode(question, forKey: .question)
    }
}


extension Faq: Identifiable {}
