//
// Flux2KleinI2I.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Flux2KleinI2I: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case flux2KleinI2I = "Flux2KleinI2I"
    }
    public var comfyRequestId: String
    /** base64 return */
    public var file: String
    /** input subject image as base64 — data URI (web) or raw base64 (android/ios); type detected server-side */
    public var image: String
    /** reference image as base64 — data URI (web) or raw base64 (android/ios); type detected server-side */
    public var image2: String
    public var prompt: String
    public var type: ModelType

    public init(comfyRequestId: String, file: String, image: String, image2: String, prompt: String, type: ModelType) {
        self.comfyRequestId = comfyRequestId
        self.file = file
        self.image = image
        self.image2 = image2
        self.prompt = prompt
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comfyRequestId = "comfy_request_id"
        case file
        case image
        case image2
        case prompt
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(comfyRequestId, forKey: .comfyRequestId)
        try container.encode(file, forKey: .file)
        try container.encode(image, forKey: .image)
        try container.encode(image2, forKey: .image2)
        try container.encode(prompt, forKey: .prompt)
        try container.encode(type, forKey: .type)
    }
}

