//
// GooglePay.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GooglePay: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case googlePay = "GooglePay"
    }
    public var credit: Int64
    public var loaded: Bool
    public var orderId: String?
    public var packageName: String
    public var productId: String
    public var purchaseToken: String
    public var type: ModelType

    public init(credit: Int64, loaded: Bool, orderId: String? = nil, packageName: String, productId: String, purchaseToken: String, type: ModelType) {
        self.credit = credit
        self.loaded = loaded
        self.orderId = orderId
        self.packageName = packageName
        self.productId = productId
        self.purchaseToken = purchaseToken
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case credit
        case loaded
        case orderId = "order_id"
        case packageName = "package_name"
        case productId = "product_id"
        case purchaseToken = "purchase_token"
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(credit, forKey: .credit)
        try container.encode(loaded, forKey: .loaded)
        try container.encodeIfPresent(orderId, forKey: .orderId)
        try container.encode(packageName, forKey: .packageName)
        try container.encode(productId, forKey: .productId)
        try container.encode(purchaseToken, forKey: .purchaseToken)
        try container.encode(type, forKey: .type)
    }
}

