//
// LyricSync.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LyricSync: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case lyricSync = "LyricSync"
    }
    /** input image as base64 — data URI (web) or raw base64 (android/ios), empty if unused; type detected server-side */
    public var audio: String
    /** return */
    public var characters: [CharacterAlignment]
    public var lyrics: String
    public var type: ModelType
    /** return */
    public var words: [WordAlignment]

    public init(audio: String, characters: [CharacterAlignment], lyrics: String, type: ModelType, words: [WordAlignment]) {
        self.audio = audio
        self.characters = characters
        self.lyrics = lyrics
        self.type = type
        self.words = words
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case audio
        case characters
        case lyrics
        case type
        case words
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(audio, forKey: .audio)
        try container.encode(characters, forKey: .characters)
        try container.encode(lyrics, forKey: .lyrics)
        try container.encode(type, forKey: .type)
        try container.encode(words, forKey: .words)
    }
}

