//
// LyricSync.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LyricSync: Sendable, Codable, Hashable {

    public var audio: String
    public var characters: [CharacterAlignment]?
    public var credit: Int64?
    public var id: UUID
    public var loss: Double?
    public var lyrics: String
    public var userId: String?
    public var words: [WordAlignment]?

    public init(audio: String, characters: [CharacterAlignment]? = nil, credit: Int64? = nil, id: UUID, loss: Double? = nil, lyrics: String, userId: String? = nil, words: [WordAlignment]? = nil) {
        self.audio = audio
        self.characters = characters
        self.credit = credit
        self.id = id
        self.loss = loss
        self.lyrics = lyrics
        self.userId = userId
        self.words = words
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case audio
        case characters
        case credit
        case id
        case loss
        case lyrics
        case userId = "user_id"
        case words
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(audio, forKey: .audio)
        try container.encodeIfPresent(characters, forKey: .characters)
        try container.encodeIfPresent(credit, forKey: .credit)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(loss, forKey: .loss)
        try container.encode(lyrics, forKey: .lyrics)
        try container.encodeIfPresent(userId, forKey: .userId)
        try container.encodeIfPresent(words, forKey: .words)
    }
}


extension LyricSync: Identifiable {}
