//
// Pay.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Pay: Sendable, Codable, Hashable {

    public var credit: Int64?
    public var currency: String?
    /** uuid v7 */
    public var id: UUID
    /** Signed transaction JWS from StoreKit; the input to Apple verification. */
    public var jws: String?
    public var loaded: Bool?
    /** Google's per-purchase `orderId`, returned by the Play Developer API (not the client). Not used for dedup — `ref_id` is — because promo-code purchases may have no `orderId`. */
    public var orderId: String?
    public var packageName: String?
    public var price: Int64?
    public var productId: String?
    /** Selects the verification path: Apple App Store vs Google Play. */
    public var provider: PayProvider
    /** Globally-unique purchase id, used as the idempotency key for both stores. Apple: the `transactionId`, extracted server-side from the verified JWS   (empty on the incoming request — the server fills it in). Google: the `purchaseToken`, sent by the client. It is both the input to   Play Developer API verification and the idempotency key. */
    public var refId: String?
    public var status: PayStatus?
    public var userId: String

    public init(credit: Int64? = nil, currency: String? = nil, id: UUID, jws: String? = nil, loaded: Bool? = nil, orderId: String? = nil, packageName: String? = nil, price: Int64? = nil, productId: String? = nil, provider: PayProvider, refId: String? = nil, status: PayStatus? = nil, userId: String) {
        self.credit = credit
        self.currency = currency
        self.id = id
        self.jws = jws
        self.loaded = loaded
        self.orderId = orderId
        self.packageName = packageName
        self.price = price
        self.productId = productId
        self.provider = provider
        self.refId = refId
        self.status = status
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case credit
        case currency
        case id
        case jws
        case loaded
        case orderId = "order_id"
        case packageName = "package_name"
        case price
        case productId = "product_id"
        case provider
        case refId = "ref_id"
        case status
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(credit, forKey: .credit)
        try container.encodeIfPresent(currency, forKey: .currency)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(jws, forKey: .jws)
        try container.encodeIfPresent(loaded, forKey: .loaded)
        try container.encodeIfPresent(orderId, forKey: .orderId)
        try container.encodeIfPresent(packageName, forKey: .packageName)
        try container.encodeIfPresent(price, forKey: .price)
        try container.encodeIfPresent(productId, forKey: .productId)
        try container.encode(provider, forKey: .provider)
        try container.encodeIfPresent(refId, forKey: .refId)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encode(userId, forKey: .userId)
    }
}


extension Pay: Identifiable {}
