//
// PayProvider.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Which app store a purchase came from. Selects the verification path in &#x60;pre&#x60;. Schema name &#x60;PayProvider&#x60; to avoid clashing with the unrelated &#x60;provider::Provider&#x60; in the OpenAPI components. */
public enum PayProvider: String, Sendable, Codable, CaseIterable {
    case apple = "Apple"
    case google = "Google"
}
