//
// Project.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Project: Sendable, Codable, Hashable {

    public var about: String
    public var audio: String
    public var audioLines: [AudioLine]
    public var faqs: [Faq]
    public var genre: String
    public var id: UUID
    public var playlist: String
    public var seasons: [Season]
    public var summary: String
    public var userId: String

    public init(about: String, audio: String, audioLines: [AudioLine], faqs: [Faq], genre: String, id: UUID, playlist: String, seasons: [Season], summary: String, userId: String) {
        self.about = about
        self.audio = audio
        self.audioLines = audioLines
        self.faqs = faqs
        self.genre = genre
        self.id = id
        self.playlist = playlist
        self.seasons = seasons
        self.summary = summary
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case about
        case audio
        case audioLines = "audio_lines"
        case faqs
        case genre
        case id
        case playlist
        case seasons
        case summary
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(about, forKey: .about)
        try container.encode(audio, forKey: .audio)
        try container.encode(audioLines, forKey: .audioLines)
        try container.encode(faqs, forKey: .faqs)
        try container.encode(genre, forKey: .genre)
        try container.encode(id, forKey: .id)
        try container.encode(playlist, forKey: .playlist)
        try container.encode(seasons, forKey: .seasons)
        try container.encode(summary, forKey: .summary)
        try container.encode(userId, forKey: .userId)
    }
}


extension Project: Identifiable {}
