//
// Revolut.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Revolut: Sendable, Codable, Hashable {

    public var amountCents: Int64
    public var credit: Int64?
    public var id: UUID
    public var loaded: Bool?
    public var paymentUrl: String?
    public var revolutOrderId: String?
    public var status: Status
    public var userId: String

    public init(amountCents: Int64, credit: Int64? = nil, id: UUID, loaded: Bool? = nil, paymentUrl: String? = nil, revolutOrderId: String? = nil, status: Status, userId: String) {
        self.amountCents = amountCents
        self.credit = credit
        self.id = id
        self.loaded = loaded
        self.paymentUrl = paymentUrl
        self.revolutOrderId = revolutOrderId
        self.status = status
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amountCents = "amount_cents"
        case credit
        case id
        case loaded
        case paymentUrl = "payment_url"
        case revolutOrderId = "revolut_order_id"
        case status
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amountCents, forKey: .amountCents)
        try container.encodeIfPresent(credit, forKey: .credit)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(loaded, forKey: .loaded)
        try container.encodeIfPresent(paymentUrl, forKey: .paymentUrl)
        try container.encodeIfPresent(revolutOrderId, forKey: .revolutOrderId)
        try container.encode(status, forKey: .status)
        try container.encode(userId, forKey: .userId)
    }
}


extension Revolut: Identifiable {}
