//
// Scene.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Scene: Sendable, Codable, Hashable {

    public var audioLineId: UUID
    public var id: UUID
    public var shots: [Shot]
    public var text: String

    public init(audioLineId: UUID, id: UUID, shots: [Shot], text: String) {
        self.audioLineId = audioLineId
        self.id = id
        self.shots = shots
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case audioLineId = "audio_line_id"
        case id
        case shots
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(audioLineId, forKey: .audioLineId)
        try container.encode(id, forKey: .id)
        try container.encode(shots, forKey: .shots)
        try container.encode(text, forKey: .text)
    }
}


extension Scene: Identifiable {}
