//
// Season.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Season: Sendable, Codable, Hashable {

    public var episodes: [Episode]
    public var id: UUID

    public init(episodes: [Episode], id: UUID) {
        self.episodes = episodes
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case episodes
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(episodes, forKey: .episodes)
        try container.encode(id, forKey: .id)
    }
}


extension Season: Identifiable {}
