//
// Shot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Shot: Sendable, Codable, Hashable {

    public var draftImage: String
    public var finalImage: String
    public var id: UUID

    public init(draftImage: String, finalImage: String, id: UUID) {
        self.draftImage = draftImage
        self.finalImage = finalImage
        self.id = id
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case draftImage = "draft_image"
        case finalImage = "final_image"
        case id
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(draftImage, forKey: .draftImage)
        try container.encode(finalImage, forKey: .finalImage)
        try container.encode(id, forKey: .id)
    }
}


extension Shot: Identifiable {}
