//
// Solana.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Solana: Sendable, Codable, Hashable {

    public var amountCents: Int64
    public var credit: Int64?
    public var id: UUID
    public var loaded: Bool?
    public var pubkey: String
    public var quotedOutUnits: Int64?
    public var requestId: String?
    public var signature: String?
    public var signedTx: String?
    public var status: Status
    public var unsignedTx: String?
    public var userId: String

    public init(amountCents: Int64, credit: Int64? = nil, id: UUID, loaded: Bool? = nil, pubkey: String, quotedOutUnits: Int64? = nil, requestId: String? = nil, signature: String? = nil, signedTx: String? = nil, status: Status, unsignedTx: String? = nil, userId: String) {
        self.amountCents = amountCents
        self.credit = credit
        self.id = id
        self.loaded = loaded
        self.pubkey = pubkey
        self.quotedOutUnits = quotedOutUnits
        self.requestId = requestId
        self.signature = signature
        self.signedTx = signedTx
        self.status = status
        self.unsignedTx = unsignedTx
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amountCents = "amount_cents"
        case credit
        case id
        case loaded
        case pubkey
        case quotedOutUnits = "quoted_out_units"
        case requestId = "request_id"
        case signature
        case signedTx = "signed_tx"
        case status
        case unsignedTx = "unsigned_tx"
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amountCents, forKey: .amountCents)
        try container.encodeIfPresent(credit, forKey: .credit)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(loaded, forKey: .loaded)
        try container.encode(pubkey, forKey: .pubkey)
        try container.encodeIfPresent(quotedOutUnits, forKey: .quotedOutUnits)
        try container.encodeIfPresent(requestId, forKey: .requestId)
        try container.encodeIfPresent(signature, forKey: .signature)
        try container.encodeIfPresent(signedTx, forKey: .signedTx)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(unsignedTx, forKey: .unsignedTx)
        try container.encode(userId, forKey: .userId)
    }
}


extension Solana: Identifiable {}
