//
// Status.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum Status: Int, Sendable, Codable, CaseIterable {
    case _1 = 1
    case _2 = 2
    case _3 = 3
}
