//
// Stripe.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Stripe: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case stripe = "Stripe"
    }
    public var amountCents: Int64
    public var credit: Int64
    public var loaded: Bool
    public var paymentUrl: String
    public var stripePaymentIntentId: String
    public var stripeSessionId: String
    public var type: ModelType

    public init(amountCents: Int64, credit: Int64, loaded: Bool, paymentUrl: String, stripePaymentIntentId: String, stripeSessionId: String, type: ModelType) {
        self.amountCents = amountCents
        self.credit = credit
        self.loaded = loaded
        self.paymentUrl = paymentUrl
        self.stripePaymentIntentId = stripePaymentIntentId
        self.stripeSessionId = stripeSessionId
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amountCents = "amount_cents"
        case credit
        case loaded
        case paymentUrl = "payment_url"
        case stripePaymentIntentId = "stripe_payment_intent_id"
        case stripeSessionId = "stripe_session_id"
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amountCents, forKey: .amountCents)
        try container.encode(credit, forKey: .credit)
        try container.encode(loaded, forKey: .loaded)
        try container.encode(paymentUrl, forKey: .paymentUrl)
        try container.encode(stripePaymentIntentId, forKey: .stripePaymentIntentId)
        try container.encode(stripeSessionId, forKey: .stripeSessionId)
        try container.encode(type, forKey: .type)
    }
}

