//
// Upload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** default values */
public struct Upload: Sendable, Codable, Hashable {

    public var credit: Int64
    public var file: String
    /** uuid v7 */
    public var id: UUID
    public var userId: String

    public init(credit: Int64, file: String, id: UUID, userId: String) {
        self.credit = credit
        self.file = file
        self.id = id
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case credit
        case file
        case id
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(credit, forKey: .credit)
        try container.encode(file, forKey: .file)
        try container.encode(id, forKey: .id)
        try container.encode(userId, forKey: .userId)
    }
}


extension Upload: Identifiable {}
