//
// Wise.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Wise: Sendable, Codable, Hashable {

    public var amountCents: Int64
    public var credit: Int64?
    public var currency: String
    public var id: UUID
    public var loaded: Bool?
    public var reference: String
    public var status: Status
    public var userId: String
    public var wiseCreditId: String?

    public init(amountCents: Int64, credit: Int64? = nil, currency: String, id: UUID, loaded: Bool? = nil, reference: String, status: Status, userId: String, wiseCreditId: String? = nil) {
        self.amountCents = amountCents
        self.credit = credit
        self.currency = currency
        self.id = id
        self.loaded = loaded
        self.reference = reference
        self.status = status
        self.userId = userId
        self.wiseCreditId = wiseCreditId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amountCents = "amount_cents"
        case credit
        case currency
        case id
        case loaded
        case reference
        case status
        case userId = "user_id"
        case wiseCreditId = "wise_credit_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amountCents, forKey: .amountCents)
        try container.encodeIfPresent(credit, forKey: .credit)
        try container.encode(currency, forKey: .currency)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(loaded, forKey: .loaded)
        try container.encode(reference, forKey: .reference)
        try container.encode(status, forKey: .status)
        try container.encode(userId, forKey: .userId)
        try container.encodeIfPresent(wiseCreditId, forKey: .wiseCreditId)
    }
}


extension Wise: Identifiable {}
