//
// WordAlignment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WordAlignment: Sendable, Codable, Hashable {

    public var end: Double
    public var loss: Double
    public var start: Double
    public var text: String

    public init(end: Double, loss: Double, start: Double, text: String) {
        self.end = end
        self.loss = loss
        self.start = start
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case end
        case loss
        case start
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(end, forKey: .end)
        try container.encode(loss, forKey: .loss)
        try container.encode(start, forKey: .start)
        try container.encode(text, forKey: .text)
    }
}

