//
// ZImageTurbo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ZImageTurbo: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case zimageturbo = "ZImageTurbo"
    }
    public var falRequestId: String
    /** base64 return */
    public var file: String
    public var prompt: String
    public var type: ModelType

    public init(falRequestId: String, file: String, prompt: String, type: ModelType) {
        self.falRequestId = falRequestId
        self.file = file
        self.prompt = prompt
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case falRequestId = "fal_request_id"
        case file
        case prompt
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(falRequestId, forKey: .falRequestId)
        try container.encode(file, forKey: .file)
        try container.encode(prompt, forKey: .prompt)
        try container.encode(type, forKey: .type)
    }
}

