import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.android.kotlin.multiplatform.library)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.composeCompiler)
    id("maven-publish")
}

group = "io.github.femimarket"
version = project.findProperty("libraryVersion") as String? ?: "local-dev"

kotlin {
    androidLibrary {
        namespace = "org.jetbrains.kotlinx.multiplatform.library.template"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        withJava()
        withHostTestBuilder {}.configure {}
        withDeviceTestBuilder {
            sourceSetTreeName = "test"
        }

        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
    }
    js {
        browser()
        useEsModules() // @JsModule("rust_ffi") in shared webMain works without @JsNonModule
    }
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
    }

    sourceSets {
        // No npm: the wasm-inlined rust_ffi.js is embedded as base64 in
        // RustFfiBundle.kt (generated by build-rust.sh) and loaded at runtime.
        webMain.dependencies {
            api(libs.compose.ui)
            implementation(libs.kotlinx.browser)
            implementation(libs.wrappers.browser)
            implementation( libs.kotlinx.io.core)
            implementation(libs.kotlinx.coroutinesCore)
            implementation(npm("mediabunny", "1.49.0"))
        }
        commonMain.dependencies {
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.coroutinesCore)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutinesTest)
        }
    }
}

// The Kotlin Multiplatform plugin auto-creates the publications (one per target + a root);
// we just point them at GitHub Packages, matching androidapps/Splash.
publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/femimarket/api")
            credentials {
                username = providers.gradleProperty("gpr.user").orNull
                    ?: System.getenv("GITHUB_ACTOR")
                password = providers.gradleProperty("gpr.key").orNull
                    ?: System.getenv("GITHUB_TOKEN")
            }
        }
    }
}
